servers:
    - host: irc.example.com
      port: 6667
      nick: brobot
      admins:
          - you
          - someone
      channels:
          - '#example'

command_plugins:
    PRIVMSG:
    PUBMSG:
    BOTH:
        - path: bot.BotPlugin
          commands:
              - bot
        - path: commands.CommandsPlugin
          commands:
              - commands
              - help
    

event_plugins:
    - name: PUBMSG
      plugins:
          - urititle.URITitlePlugin

plugin_path: plugins
command_prefix: '!'
version_string: brobot v1.0
